services:
  - type: web
    name: redxminibot-ultra
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node --expose-gc index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_NAME
        value: 🔥 REDXMINIBOT ULTRA 🔥
      - key: PREFIX
        value: "."
      - key: BOT_MODE
        value: public
      - key: PORT
        value: "3000"
